### ISSUE TITLE
No Password's in Passwords.txt/Write Error

### ISSUE THREAD

**Issue by mesiapk** [digitalocean/do_user_scripts#25]
When trying to delete/add a plugin, I am prompted with a "Connection Information" screen, which ask for FTP information (which doesn't work) [Most likely a(n) write error (upon creation of the droplet using the userscript, I get "Broken Pipe" and "Write Error" )]

When looking usr/root/passwords.txt I find:

"Root MySQL Password"
"Wordpress MySQL Password"

With no password following them. (Line 13/14 in the user script)

**Comment by andrewsomething** [comment]
Thanks for the report. Which script and which distro version are you using?

**Comment by mesiapk** [comment]
Hehe, sorry forgot that :D 

https://github.com/digitalocean/do_user_scripts/blob/master/CentOS-7/cms/wordpress-nginx.yml

**Comment by andrewsomething** [comment]
Ah, got it. Looks like a simple typo. PR to fix in #26 Thanks again!
