### ISSUE TITLE
Can't get shell scripts to run via the REST API

### ISSUE THREAD

**Issue by dukedougal** [digitalocean/do_user_scripts#46]
I POST the following data to https://api.digitalocean.com/v2/droplets

{"name":"1470293222","image":"ubuntu-16-04-x64","size":"512mb","user_data":"#!/bin/bash\ncurl http://www.myserver.com","region":"nyc1"}

This should create a new droplet and run the script in user_data, but no matter what I do, I can't seem to get the script to run.

Strangely if I launch a Droplet from the Digital Ocean console - which appears NOT to use the REST API, then the userdata script appears to work OK

Anyone got any idea how to make a Digital Ocean boot script work?

**Comment by andrewsomething** [comment]
Hey @dukedougal, could you post the actual command or code used to POST that? I don't see anything wrong with the json itself. For instance, this works:

```
curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $DO_TOKEN"     -d '{"name":"test","image":"ubuntu-16-04-x64","size":"512mb","user_data":"#!/bin/bash\ntouch /root/foo","region":"nyc1"}'  "https://api.digitalocean.com/v2/droplets"
```

The files `/var/log/cloud-init-output.log` and `/var/log/cloud-init.log` might also shed some light.

**Comment by dukedougal** [comment]
It's working now thanks please close.

**Comment by andrewsomething** [comment]
Glad to hear you got it working!
